version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_DB: bortube-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
    driver: local
